version: "3.9"
services:
  db:
    build: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: app
    volumes:
      - ./app:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
#  web:
#    build: web
#    ports:
#      - "443:443"
#    depends_on:
#      - db
#      - app